import React, { Fragment } from "react";
import './sidebars.css'
// import './sidebars.js'
// import './NewPage.css'

const NewPage = () => {
    return (
        <Fragment>

                <div id="myDiv">
                    <div className="scroll-area">
                        <p className="text-end ">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reiciendis soluta laboriosam nihil fuga quisquam, corporis incidunt rem labore repellat non tempore, officiis fugit quam quos, architecto illum nostrum doloribus quidem?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut nam ipsam iste nesciunt, ducimus, quam, aperiam rem quas quod quaerat dolor fugiat pariatur iure laborum? Quae deserunt inventore perferendis at libero soluta consequuntur quam accusamus asperiores placeat magni, dignissimos culpa pariatur ipsum sequi sunt error laborum nam odit molestias aperiam iure. Nam quidem commodi magni quo libero reprehenderit iusto ab asperiores facere, esse distinctio nemo ratione eaque suscipit vero deserunt voluptas sapiente! Natus excepturi ullam temporibus nihil tenetur repellat laborum, odit animi minus. Nam deleniti velit placeat hic quia vero porro, animi illo doloremque cupiditate quidem, sunt cumque. Sunt, consequuntur.</p>
                        <p className="text-end ">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reiciendis soluta laboriosam nihil fuga quisquam, corporis incidunt rem labore repellat non tempore, officiis fugit quam quos, architecto illum nostrum doloribus quidem?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut nam ipsam iste nesciunt, ducimus, quam, aperiam rem quas quod quaerat dolor fugiat pariatur iure laborum? Quae deserunt inventore perferendis at libero soluta consequuntur quam accusamus asperiores placeat magni, dignissimos culpa pariatur ipsum sequi sunt error laborum nam odit molestias aperiam iure. Nam quidem commodi magni quo libero reprehenderit iusto ab asperiores facere, esse distinctio nemo ratione eaque suscipit vero deserunt voluptas sapiente! Natus excepturi ullam temporibus nihil tenetur repellat laborum, odit animi minus. Nam deleniti velit placeat hic quia vero porro, animi illo doloremque cupiditate quidem, sunt cumque. Sunt, consequuntur.</p>
                        <p className="text-end ">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reiciendis soluta laboriosam nihil fuga quisquam, corporis incidunt rem labore repellat non tempore, officiis fugit quam quos, architecto illum nostrum doloribus quidem?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut nam ipsam iste nesciunt, ducimus, quam, aperiam rem quas quod quaerat dolor fugiat pariatur iure laborum? Quae deserunt inventore perferendis at libero soluta consequuntur quam accusamus asperiores placeat magni, dignissimos culpa pariatur ipsum sequi sunt error laborum nam odit molestias aperiam iure. Nam quidem commodi magni quo libero reprehenderit iusto ab asperiores facere, esse distinctio nemo ratione eaque suscipit vero deserunt voluptas sapiente! Natus excepturi ullam temporibus nihil tenetur repellat laborum, odit animi minus. Nam deleniti velit placeat hic quia vero porro, animi illo doloremque cupiditate quidem, sunt cumque. Sunt, consequuntur.</p>
                        <p className="text-end ">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reiciendis soluta laboriosam nihil fuga quisquam, corporis incidunt rem labore repellat non tempore, officiis fugit quam quos, architecto illum nostrum doloribus quidem?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut nam ipsam iste nesciunt, ducimus, quam, aperiam rem quas quod quaerat dolor fugiat pariatur iure laborum? Quae deserunt inventore perferendis at libero soluta consequuntur quam accusamus asperiores placeat magni, dignissimos culpa pariatur ipsum sequi sunt error laborum nam odit molestias aperiam iure. Nam quidem commodi magni quo libero reprehenderit iusto ab asperiores facere, esse distinctio nemo ratione eaque suscipit vero deserunt voluptas sapiente! Natus excepturi ullam temporibus nihil tenetur repellat laborum, odit animi minus. Nam deleniti velit placeat hic quia vero porro, animi illo doloremque cupiditate quidem, sunt cumque. Sunt, consequuntur.</p>
                        <p className="text-end ">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reiciendis soluta laboriosam nihil fuga quisquam, corporis incidunt rem labore repellat non tempore, officiis fugit quam quos, architecto illum nostrum doloribus quidem?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut nam ipsam iste nesciunt, ducimus, quam, aperiam rem quas quod quaerat dolor fugiat pariatur iure laborum? Quae deserunt inventore perferendis at libero soluta consequuntur quam accusamus asperiores placeat magni, dignissimos culpa pariatur ipsum sequi sunt error laborum nam odit molestias aperiam iure. Nam quidem commodi magni quo libero reprehenderit iusto ab asperiores facere, esse distinctio nemo ratione eaque suscipit vero deserunt voluptas sapiente! Natus excepturi ullam temporibus nihil tenetur repellat laborum, odit animi minus. Nam deleniti velit placeat hic quia vero porro, animi illo doloremque cupiditate quidem, sunt cumque. Sunt, consequuntur.</p>
                        <p className="text-end ">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reiciendis soluta laboriosam nihil fuga quisquam, corporis incidunt rem labore repellat non tempore, officiis fugit quam quos, architecto illum nostrum doloribus quidem?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut nam ipsam iste nesciunt, ducimus, quam, aperiam rem quas quod quaerat dolor fugiat pariatur iure laborum? Quae deserunt inventore perferendis at libero soluta consequuntur quam accusamus asperiores placeat magni, dignissimos culpa pariatur ipsum sequi sunt error laborum nam odit molestias aperiam iure. Nam quidem commodi magni quo libero reprehenderit iusto ab asperiores facere, esse distinctio nemo ratione eaque suscipit vero deserunt voluptas sapiente! Natus excepturi ullam temporibus nihil tenetur repellat laborum, odit animi minus. Nam deleniti velit placeat hic quia vero porro, animi illo doloremque cupiditate quidem, sunt cumque. Sunt, consequuntur.</p>
                        <p className="text-end ">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reiciendis soluta laboriosam nihil fuga quisquam, corporis incidunt rem labore repellat non tempore, officiis fugit quam quos, architecto illum nostrum doloribus quidem?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut nam ipsam iste nesciunt, ducimus, quam, aperiam rem quas quod quaerat dolor fugiat pariatur iure laborum? Quae deserunt inventore perferendis at libero soluta consequuntur quam accusamus asperiores placeat magni, dignissimos culpa pariatur ipsum sequi sunt error laborum nam odit molestias aperiam iure. Nam quidem commodi magni quo libero reprehenderit iusto ab asperiores facere, esse distinctio nemo ratione eaque suscipit vero deserunt voluptas sapiente! Natus excepturi ullam temporibus nihil tenetur repellat laborum, odit animi minus. Nam deleniti velit placeat hic quia vero porro, animi illo doloremque cupiditate quidem, sunt cumque. Sunt, consequuntur.</p>
                    </div>
                </div>
        </Fragment>
    )
}

export default NewPage